### ISSUE TITLE
Column doesn't propagate changes

### ISSUE THREAD

**Issue by aloscha** [Juicy/juicy-table-repeat#1]
The problem occurs when in each rows we can do some changes and result doesn't propagate changes.
So ex. we have row with two columns

> `<div class="column">{{item.Quantity$}}</div>`
> `<div class="column"><button value="{{item.AddQuantity$::click}}" onmousedown="++this.value"/>Add quantity</button></div>`

In server side I add Quantity + 1:

> public void Handle(Input.AddQuantity action){
>    Quantity++;
> }

All patches looks good, but value in `{{item.Quantity$}}` doesn't increased

**Comment by miyconst** [comment]
@aloscha could you please prepare a jsfiddle?

**Comment by aloscha** [comment]
No problem @miyconst here you go: https://jsfiddle.net/79scqLj1/

**Comment by aloscha** [comment]
up

**Comment by miyconst** [comment]
@aloscha sorry for the late reply, somehow I missed your answer. Unfortunately it is not supported right now, only array splices are observed right now. I will check whether it is easy to implement this feature.

**Comment by miyconst** [comment]
@aloscha I have added this feature and released `juicy-table-repeat#0.0.1`, now your jsfiddle works.

**Comment by tomalec** [comment]
The given fix re-stamps table on every change what breaks UX completely when there is an input bound on keystroke, plus it's a performance hit.

**Comment by miyconst** [comment]
@tomalec this workaround element was never intended to be fully functional. I made it in a couple of hours for a specific need. Do you think it worth to spend time fixing it?

**Comment by tomalec** [comment]
I think so. We need to use it in Demo, and it needs to be fully functional.
I've already spend 2hrs and got the fix, just need some time to merge it, so it should be today EOD

**Comment by miyconst** [comment]
Okay, let me know if need any help from me.
