### ISSUE TITLE
Should this element be used in Starcounter apps

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-table-repeat#11]
This element is used few Starcounter apps. From README.md, I understand that it is only needed for supporting IE. Since we don't support IE anymore, can this element be removed from the apps?

@Mihaiii could you please research that.

**Comment by Mihaiii** [comment]
`Juicy-table-repeat` is currently used in 2 StarcounterApps:
- Barcodes
- Products

I checked the behavior before and after removing it in **Chrome**, **Firefox**, **Edge**.
It is safe to remove `juicy-table-repeat`.

I made 2 PRs in this sense:

- https://github.com/StarcounterApps/Barcodes/pull/23
- https://github.com/StarcounterApps/Products/pull/56

**Comment by warpech** [comment]
Awesome! When the two above PRs are merged, the topic `used-in-starcounter-app` can be removed from https://github.com/Juicy/juicy-table-repeat/

**Comment by Mihaiii** [comment]
Closing as done.
