### ISSUE TITLE
dom-repeat on td?

### ISSUE THREAD

**Issue by jay8t6** [Juicy/juicy-table-repeat#7]
What if we were to do a dom-repeat on `<td>` tags, how do we go about it? Does your element support that?

**Comment by miyconst** [comment]
I am afraid that it won't work in IE. The `juicy-table-repeat` element never intended to replace the standard `dom-repeat` element from Polymer. It is just a workaround to render simple HTML tables in IE.

Feel free to implement this feature and rise a pull request :).
