### ISSUE TITLE
Component not registered on Bower

### ISSUE THREAD

**Issue by madeleineostoja** [Juicy/juicy-table-repeat#9]
Just an FYI `bower install juicy-table-repeat` comes up blank, looks like the component isn't registered in the [Bower registry](https://bower.io/).

You can still install the package from Github with `bower install Juicy/juicy-table-repeat`, but either the README needs updating or it needs to be added to the Bower registry.

**Comment by miyconst** [comment]
@seaneking thank you for pointing that out. The readme is now updated.
